### PR TITLE
started w changes

### PR DESCRIPTION
**Pull request by timriffe**
added MortalitySmooth to global.R
added items to todo.txt
created local file (ignored) in order to have live objects for testing. still in progress

### CODE REVIEW

**Comment by timriffe** [comment]
more changes in several files, most notably prepare_data.R

**Comment by timriffe** [comment]
Hi Jorge,
I think it's time for you to have a look. I think it's possible I've thrown off the Lexis alignment (or fixed it?), but anyway it still runs. There's a lot for you to review now. Maybe best to keep this in a branch until you cna have a look. Right now smoothing is set to `FALSE`. If the user selects `TRUE`, then it couldn't hurt to have a box for them to enter a smoothing parameter lambda, which right now is set to 1 as its defaultf, but I made it an optional argument. Right now the object `pop_long` contains all data info required to make the plots (except ratios might need a redux in the long format. I suggest ratio calcs to happen in `prepare_data.R` not sure where they are now. Can call sometime to review together if you like.
Best,
Tim

**Comment by cimentadaj** [comment]
I pulled your changes to a branch on my repo and I've changed some stuff to wrap it up. I should be done by today, hopefully.

**Comment by cimentadaj** [comment]
After merging, I had to apply some changes to keep the same results as before:

* I had to change some stuff to keep the upper left triangle as before because some reviewers had already discussed the top left triangle and we answered discussing it as well. All in all, we needed it back.

* Somewhere we broke some of gender difference code because we now have a new `pop_ch` data frame. I adapted all code so that they work and some parts are now rewritten in tidy verbs.

* Removed the gender difference indicator because I can't get the legend to work.  Sebastian said he would check it out but in the mean time I'll keep it excluded.

* Introduced the smooth button in the user interface. Note that I had to remove two specifics lines of code which were giving me some errors AFTER I changed your code to keep the above working. Lines are:
https://github.com/cimentadaj/lexis_plot/blob/master/aux_scripts/prepare_data.R#L113-L114

I can't figure out what the `test` object is on the last line and I can't understand why you're using `anti_join` here. In any case, shouldn't it be `semi_join` or `left_join`? The first, in case we just want to have the same rows as in `cmx`, or `left_join` if we want to autocomplete the missing years/cohorts.

Note that this last point is **important** because I think I might've rendered the smoothing useless without these lines. Check it out when you can. I'll write the reviewers letter tomorrow so that we send it by tomorrow and keep adding stuff to the app where we think we need to.

**Pull request merged**
